### ISSUE TITLE
LoginBase.php fatal error: array_filter(): Argument #1 ($array) must be of type array, null given

### ISSUE THREAD

**Issue by ktmn** [hCaptcha/hcaptcha-wordpress-plugin#289]
```
Uncaught TypeError: array_filter(): Argument #1 ($array) must be of type array, null given in /public_html/wp-content/plugins/hcaptcha-for-forms-and-more/src/php/Abstracts/LoginBase.php:142
Stack trace:
#0 /public_html/wp-content/plugins/hcaptcha-for-forms-and-more/src/php/Abstracts/LoginBase.php(142): array_filter(NULL, Object(Closure))
#1 /public_html/wp-content/plugins/hcaptcha-for-forms-and-more/src/php/Abstracts/LoginBase.php(112): HCaptcha\Abstracts\LoginBase->is_login_limit_exceeded()
#2 /public_html/wp-content/plugins/hcaptcha-for-forms-and-more/src/php/WP/Login.php(46): HCaptcha\Abstracts\LoginBase->add_captcha()
#3 /public_html/wp-includes/class-wp-hook.php(310): HCaptcha\WP\Login->add_captcha('')
#4 /public_html/wp-includes/class-wp-hook.php(334): WP_Hook->apply_filters('', Array)
#5 /public_html/wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#6 /public_html/wp-login.php(1447): do_action('login_form')
#7 {main}
  thrown
```

```
-- hCaptcha Info --

Version:                              3.3.3
Site key:                             Set
Secret key:                           Set
Theme:                                light
Size:                                 normal
Language:                             Auto-detect
Mode:                                 live
Custom Themes:                        Off
Config Params:                        Not set
Turn Off When Logged In:              Off
Disable reCAPTCHA Compatibility:      On
Whitelisted IPs:                      Not set
Login attempts before hCaptcha:       3
Failed login attempts interval, min:  15
Delay showing hCaptcha, ms:           -100

--- Active plugins and themes ---

Contact Form 7:                       
  Form:                               On
WP Core:                              
  Comment Form:                       On
  Login Form:                         On
  Lost Password Form:                 On
  Post/Page Password Form:            On
  Register Form:                      On

-- Site Info --

Multisite:                            No

-- WordPress Configuration --

Version:                              6.3.2

-- Webserver Configuration --

PHP Version:                          8.0.30
```

**Comment by kagg-design** [comment]
Thank you for the report.

I wonder how this could happen... Anyway, I made a fix to avoid a fatal error in the `is_login_limit_exceeded()`. v3.4.0 should be published tomorrow.
