### ISSUE TITLE
Issue: hCaptcha plugin breaks formatting on activation with Divi theme builder

### ISSUE THREAD

**Issue by cecil6** [hCaptcha/hcaptcha-wordpress-plugin#348]
Hi,

We're having a critical issue with the hCaptcha plugin on our WordPress site (using Divi theme builder). When the plugin is activated, it breaks the entire site.

Screenshot 1: Site with hCaptcha activated (broken layout).
![broken-site](https://github.com/hCaptcha/hcaptcha-wordpress-plugin/assets/6430463/43c2dbb1-6205-4a5f-8659-6b9a69f36c1b)

Screenshot 2: Site with hCaptcha deactivated (normal state).
![without hcaptcha-plugin-min](https://github.com/hCaptcha/hcaptcha-wordpress-plugin/assets/6430463/57c9e2db-5fbc-4ae5-a2af-f215b6124396)

This issue never occurred in earlier versions, but it's been happening recently. As soon the plugin gets activated, only the form without any styling is visible. We were advised to open an issue here.  Any updates planed or available?

Thanks!

**Comment by kagg-design** [comment]
Hi, 

Thank you for the report. Could you provide the test information from the System Info admin page?

Also, there should be an error in the debug.log. Can we see it?

Many thanks.

**Comment by cecil6** [comment]
as soon as i activate the Form embed toggle to activate the captcha in my wp forms. the site breaks with the message "there was an error"

Log:
`[13-Jul-2024 16:56:43 UTC] PHP Fatal error:  Uncaught Error: Call to undefined function HCaptcha\WPForms\wpforms_get_captcha_settings() in /homepages/44/d960460507/htdocs/wp-content/plugins/hcaptcha-for-forms-and-more/src/php/WPForms/Form.php:361
Stack trace:
#0 /homepages/44/d960460507/htdocs/wp-content/plugins/hcaptcha-for-forms-and-more/src/php/WPForms/Form.php(339): HCaptcha\WPForms\Form->form_has_hcaptcha()
#1 /homepages/44/d960460507/htdocs/wp-content/plugins/hcaptcha-for-forms-and-more/src/php/WPForms/Form.php(309): HCaptcha\WPForms\Form->show_hcaptcha()
#2 /homepages/44/d960460507/htdocs/wp-includes/class-wp-hook.php(324): HCaptcha\WPForms\Form->wpforms_frontend_output()
#3 /homepages/44/d960460507/htdocs/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters()
#4 /homepages/44/d960460507/htdocs/wp-includes/plugin.php(517): WP_Hook->do_action()
#5 /homepages/44/d960460507/htdocs/wp-content/plugins/wpforms/includes/class-frontend.php(305): do_action()
#6 /homepages/44/d960460507/htdocs/wp-content/plugins/wpforms/includes/class-frontend.php(14 in /homepages/44/d960460507/htdocs/wp-content/plugins/hcaptcha-for-forms-and-more/src/php/WPForms/Form.php on line 361
[13-Jul-2024 16:56:55 UTC] PHP Fatal error:  Uncaught Error: Call to undefined function HCaptcha\WPForms\wpforms_get_captcha_settings() in /homepages/44/d960460507/htdocs/wp-content/plugins/hcaptcha-for-forms-and-more/src/php/WPForms/Form.php:400
Stack trace:
#0 /homepages/44/d960460507/htdocs/wp-content/plugins/hcaptcha-for-forms-and-more/src/php/WPForms/Form.php(61): HCaptcha\WPForms\Form->is_wpforms_provider_hcaptcha()
#1 /homepages/44/d960460507/htdocs/wp-content/plugins/hcaptcha-for-forms-and-more/src/php/WPForms/Form.php(49): HCaptcha\WPForms\Form->init_hooks()
#2 /homepages/44/d960460507/htdocs/wp-content/plugins/hcaptcha-for-forms-and-more/src/php/Main.php(1309): HCaptcha\WPForms\Form->__construct()
#3 /homepages/44/d960460507/htdocs/wp-includes/class-wp-hook.php(324): HCaptcha\Main->load_modules()
#4 /homepages/44/d960460507/htdocs/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters()
#5 /homepages/44/d960460507/htdocs/wp-includes/plugin.php(517): WP_Hook->do_action()
#6 /homepages/44/d960460507/htdocs/wp-settings.php(550): do_action()
# in /homepages/44/d960460507/htdocs/wp-content/plugins/hcaptcha-for-forms-and-more/src/php/WPForms/Form.php on line 400
[13-Jul-2024 16:56:55 UTC] PHP Notice:  Die Funktion is_embed wurde fehlerhaft aufgerufen. Bedingte Abfragen (Conditional Tags) funktionieren nicht, wenn die Beitrags-Abfrage (query_posts) noch nicht durchgeführt wurde. Sie geben dann immer 'false' zurück. Weitere Informationen: <a>Debugging in WordPress (engl.)</a>. (Diese Meldung wurde in Version 3.1.0 hinzugefügt.) in /homepages/44/d960460507/htdocs/wp-includes/functions.php on line 6078
[13-Jul-2024 16:56:55 UTC] PHP Notice:  Die Funktion is_search wurde fehlerhaft aufgerufen. Bedingte Abfragen (Conditional Tags) funktionieren nicht, wenn die Beitrags-Abfrage (query_posts) noch nicht durchgeführt wurde. Sie geben dann immer 'false' zurück. Weitere Informationen: <a>Debugging in WordPress (engl.)</a>. (Diese Meldung wurde in Version 3.1.0 hinzugefügt.) in /homepages/44/d960460507/htdocs/wp-includes/functions.php on line 6078
[13-Jul-2024 16:56:56 UTC] PHP Fatal error:  Uncaught Error: Call to undefined function HCaptcha\WPForms\wpforms_get_captcha_settings() in /homepages/44/d960460507/htdocs/wp-content/plugins/hcaptcha-for-forms-and-more/src/php/WPForms/Form.php:400
Stack trace:
#0 /homepages/44/d960460507/htdocs/wp-content/plugins/hcaptcha-for-forms-and-more/src/php/WPForms/Form.php(61): HCaptcha\WPForms\Form->is_wpforms_provider_hcaptcha()
#1 /homepages/44/d960460507/htdocs/wp-content/plugins/hcaptcha-for-forms-and-more/src/php/WPForms/Form.php(49): HCaptcha\WPForms\Form->init_hooks()
#2 /homepages/44/d960460507/htdocs/wp-content/plugins/hcaptcha-for-forms-and-more/src/php/Main.php(1309): HCaptcha\WPForms\Form->__construct()
#3 /homepages/44/d960460507/htdocs/wp-includes/class-wp-hook.php(324): HCaptcha\Main->load_modules()
#4 /homepages/44/d960460507/htdocs/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters()
#5 /homepages/44/d960460507/htdocs/wp-includes/plugin.php(517): WP_Hook->do_action()
#6 /homepages/44/d960460507/htdocs/wp-settings.php(550): do_action()
# in /homepages/44/d960460507/htdocs/wp-content/plugins/hcaptcha-for-forms-and-more/src/php/WPForms/Form.php on line 400
[13-Jul-2024 16:56:56 UTC] PHP Notice:  Die Funktion is_embed wurde fehlerhaft aufgerufen. Bedingte Abfragen (Conditional Tags) funktionieren nicht, wenn die Beitrags-Abfrage (query_posts) noch nicht durchgeführt wurde. Sie geben dann immer 'false' zurück. Weitere Informationen: <a>Debugging in WordPress (engl.)</a>. (Diese Meldung wurde in Version 3.1.0 hinzugefügt.) in /homepages/44/d960460507/htdocs/wp-includes/functions.php on line 6078
[13-Jul-2024 16:56:56 UTC] PHP Notice:  Die Funktion is_search wurde fehlerhaft aufgerufen. Bedingte Abfragen (Conditional Tags) funktionieren nicht, wenn die Beitrags-Abfrage (query_posts) noch nicht durchgeführt wurde. Sie geben dann immer 'false' zurück. Weitere Informationen: <a>Debugging in WordPress (engl.)</a>. (Diese Meldung wurde in Version 3.1.0 hinzugefügt.) in /homepages/44/d960460507/htdocs/wp-includes/functions.php on line 6078
`

**Comment by cecil6** [comment]
When i add the shortcode manualy to the form it appears 2 times and none of the captchas are working

<img width="1410" alt="image" src="https://github.com/user-attachments/assets/6ae48257-5797-42b6-b3cb-cf6ed8052b81">

**Comment by cecil6** [comment]
Hello?

**Comment by kagg-design** [comment]
I have missed your previous message. Will investigate and reply; thanks.

**Comment by kagg-design** [comment]
The problem is in the heavily outdated WPForms version. You use 1.6.2, dated Aug 2020 (almost **four years ago**). It does not have a function named `wpforms_get_captcha_settings()`. We cannot support, unfortunately, an ancient version of a 3rd-party plugin.

Please update WPForms to the current v1.8.9.6. Thank you.
